# Catppuccin Mocha — Hyprland colors
$activeBorderColor = rgba(89b4faee) rgba(cba6f7ee) 45deg
$inactiveBorderColor = rgba(45475aaa)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}
group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
    col.border_locked_active = $activeBorderColor
    col.border_locked_inactive = $inactiveBorderColor
}
