---
efi:
  mountPoint: "/boot/efi"
userSwapChoices: [ none, small ]
drawNestedPartitions: true
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]
