---
units:
  - name: NetworkManager.service
    action: enable
  - name: gdm.service
    action: enable
  - name: veloguard-update.timer
    action: enable
  - name: veloguard-wifi-autodetect.service
    action: enable
